workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      android_signing:
        - helpables_app
      groups:
        - google_credentials # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "com.helpables.app"
        GOOGLE_PLAY_TRACK: "internal"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - cliqueadmin@helpables.org
          - anam@helpables.org
          - sheza@helpables.org
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
  ios-testflight:
    name: iOS TestFlight Upload
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Codemagic Key
    environment:
        groups:
              - ios_code_signing
              - appstore_credentials 
      vars:
        BUNDLE_ID: "com.helpables.app"
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ipa \
            --release \
            --export-method app-store \
            --build-name=$FLUTTER_BUILD_NAME \
            --build-number=$FLUTTER_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        
        submit_to_testflight: true
        
