workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      android_signing:
        - helpables_app
      groups:
        - google_credentials # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "com.helpables.app" # <-- Put your package name here
        GOOGLE_PLAY_TRACK: "internal"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - cliqueadmin@helpables.org
          - anam@helpables.org
          - sheza@helpables.org
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
        
        workflows:
  ios:
    name: Build and Upload Helpables to TestFlight
    platform: ios
    flutter: stable
    sdk: iphoneos
    environment:
      vars:
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get  # Install dependencies for Flutter
      - name: Build the iOS app
        script: |
          flutter build ios --release --no-codesign  # Build without signing (Codemagic handles signing)
    build:
      ios:
        targets:
          - "Runner"
        configuration: Release
    publish:
      app_store_connect:
        api_key_id: 4LT664UP5M  # Replace with your App Store Connect API Key ID
        issuer_id: 1c9faeaf-068e-4d60-811e-60f2db7f1392  # Replace with your App Store Connect Issuer ID
        ipa_path: build/ios/ipa/Runner.ipa  # Path to the generated IPA file
        skip_submission: false  # Set to 'false' to submit the app to TestFlight automatically
        skip_waiting_for_build_processing: false  # Ensure the build is processed before submission
        notify_testers: true  # Notifies testers when the app is uploaded to TestFlight






