// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd_PH_YOBYYbdMS8cGtJn0MBsQ2yv7sZw',
    appId: '1:58094471368:android:d8d5768d1214c546667dfd',
    messagingSenderId: '58094471368',
    projectId: 'aid-request-app',
    storageBucket: 'aid-request-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHjXiz6JHG9lVNBUESMXoUQI85zuvQQw',
    appId: '1:58094471368:ios:b56cc954479d1c6c667dfd',
    messagingSenderId: '58094471368',
    projectId: 'aid-request-app',
    storageBucket: 'aid-request-app.firebasestorage.app',
    androidClientId: '58094471368-linionqu1h7dlentkrt1ppbri9imrnfj.apps.googleusercontent.com',
    iosClientId: '58094471368-skpsdgfgsirp79p4rmv1c3ve2j35ev8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.aidApp',
  );
}
