platform :ios, '13.0'
use_frameworks!  # Required for Firebase

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# Force all pods to use iOS 13.0
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
  flutter_additional_ios_build_settings(target)
end
